=== apache/river-container/river-container-core/src/main/xsd/config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
    targetNamespace="http://river.apache.org/xml/ns/container/config/1.0"
    xmlns:tns="http://river.apache.org/xml/ns/container/config/1.0"
    jaxb:version="2.0" elementFormDefault="qualified">
    <xsd:element name="container-config">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="tns:classpath" maxOccurs="unbounded" minOccurs="0"/>
                <xsd:choice maxOccurs="unbounded">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <jaxb:property name="elements"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                    <xsd:element ref="tns:property"/>
                    <xsd:element ref="tns:component"/>
                    <xsd:element name="discovery-context"
                    type="tns:DiscoveryContextType"/>
                </xsd:choice>
                
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="DiscoveryContextType">
        <xsd:sequence>
            <xsd:element name="locator" type="xsd:anyURI" minOccurs="0"
            maxOccurs="unbounded"/>
            <xsd:element name="group" type="xsd:string" minOccurs="0"
            maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
    </xsd:complexType>
    
    <xsd:element name="classpath">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="id" use="required" type="xsd:string"/>
                    <xsd:attribute name="parent" use="optional" type="xsd:string"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="codebase" type="xsd:string"/>

    <xsd:element name="property">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
            <xsd:attribute name="value" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="component">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="tns:property" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="optional"/>
            <xsd:attribute name="class" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="service-starter-config">
        <xsd:annotation>
            <xsd:documentation>
                This element is used in the configuration file for the
                service-starter service deployer component.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="tns:classpath" minOccurs="0"/>
                <xsd:element ref="tns:codebase" minOccurs="0"/>
                <xsd:choice maxOccurs="unbounded">
                    <xsd:annotation>
                        <xsd:appinfo>
                            <jaxb:property name="elements"/>
                        </xsd:appinfo>
                    </xsd:annotation>
                    <xsd:element name="discovery-context"
                    type="tns:DiscoveryContextType"/>
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== apache/river-container/river-container-core/src/main/resources/org/apache/river/container/core-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : config.xml
    Created on : December 10, 2010, 6:39 PM
    Author     : trasukg
    Description:
        This is the core configuration that is processed by the
        Bootstrap system prior to processing the profile's config.xml

        Items defined in this config are subject to being overwritten by the
        profile's config (e.g. classpath or properties settings).  As such,
        this is a good place to set defaults.

        It also gives a spot to include elements that are required in every
        profile, for instance the AnnotatedClassDeployer and MBeanRegistrar.
-->

<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership. The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License. You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

 -->

<cfg:container-config  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:cfg='http://river.apache.org/xml/ns/container/config/1.0'
   xsi:schemaLocation='http://river.apache.org/xml/ns/container/config/1.0 file:/home/trasukg/development/surrogate/src/schemas/config.xsd'>
    <!-- Dynamic policy provider needs to be available to both the container and
    any "application" classloaders, so it needs to be in a classloader which is
    a parent to both the container classloader and the application loaders.
    In traditional Jini usage, jsk-policy.jar was put into the extensions directory,
    hence was available in the "extensions" loader.  Here, we'd prefer not to 
    require any changes to the JSDK installation directory.
    -->
    <cfg:classpath id="systemClassLoader">lib/jsk-policy-${jsk-version}.jar</cfg:classpath>
    <cfg:classpath id="containerClassLoader" parent="systemClassLoader">
        lib/river-container-core-${project.version}.jar
        lib/commons-logging-1.1.1.jar
        lib/commons-vfs2-2.0.jar
        lib/jsk-platform-${jsk-version}.jar
        lib/jsk-lib-${jsk-version}.jar
        lib/jsk-resources-${jsk-version}.jar
        lib/regexp-1.3.jar
        lib/river-hsm-${project.version}.jar
        lib/admin-svc-api-${project.version}.jar
    </cfg:classpath>

    <!--cfg:component class="org.apache.river.container.ShowContextToConsole"/-->
    <cfg:component class="org.apache.river.container.AnnotatedClassDeployer"/>

    <cfg:component class="org.apache.river.container.security.SecurityInitializer"/>
    
    <cfg:component class="org.apache.river.container.el.ArgsParserImpl"/>
    
    <cfg:property name="deploymentDirectory" value="deploy"/>

    <cfg:component class="org.apache.river.container.MessagesResource"/>
    <cfg:component class="org.apache.river.container.SystemClassloaderInitializer"/>
    <cfg:component class="org.apache.river.container.CommandLineArgumentParser"/>
    <cfg:component class="org.apache.river.container.MBeanRegistrar"/>
    <cfg:component class="org.apache.river.container.ShutdownListener"/>
    <cfg:component class="org.apache.river.container.FileUtilityImpl"
        name="fileUtility"/>
    <cfg:component class="org.apache.river.container.PropertiesFileReader"/>
    <cfg:component class="org.apache.river.container.ProfileConfigReader"/>

</cfg:container-config>

=== apache/river-container/river-container-core/src/test/resources/org/apache/river/container/config/config-test-doc.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : config-test-doc.xml
    Created on : November 24, 2010, 4:13 PM
    Author     : trasukg
    Description:
        Purpose of the document follows.
-->

<cfg:container-config  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:cfg='http://river.apache.org/xml/ns/container/config/1.0'
   xsi:schemaLocation='http://river.apache.org/xml/ns/container/config/1.0 file:/home/trasukg/development/surrogate/schemas/config.xsd'>
    <cfg:classpath id="a">lib/abc.jar</cfg:classpath>
    <cfg:classpath id="b" parent="a">lib/def.jar</cfg:classpath>

    <cfg:discovery-context name="default">
        <cfg:locator></cfg:locator>
        <cfg:group></cfg:group>
    </cfg:discovery-context>

    <cfg:property name="abc" value="def"/>

    <cfg:component class="org.apache.SomethingOrOther"/>

</cfg:container-config>

=== apache/river-container/product/src/main/root/profile/outrigger/config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : config.xml
    Created on : December 10, 2010, 6:39 PM
    Author     : trasukg
    Description:
        Configuration file in the 'profile' directory selected by the 
        command line.
-->
<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership. The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License. You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

 -->

<cfg:container-config  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:cfg='http://river.apache.org/xml/ns/container/config/1.0'
   xsi:schemaLocation='http://river.apache.org/xml/ns/container/config/1.0 file:/home/trasukg/development/surrogate/src/schemas/config.xsd'>
    <cfg:property name="deploymentDirectory" value="deploy"/>

    <cfg:property name="defaultDiscoveryGroup" value="RiverContainerDefault"/>
    <cfg:component class="org.apache.river.container.work.ContextualWorkManager"/>
    <cfg:component class="org.apache.river.container.work.BasicWorkManager"/>
    <cfg:component class="org.apache.river.container.codebase.ClassServer"/>

    <!-- Deployer for 'service-starter'-style applications. -->
    <cfg:component class="org.apache.river.container.deployer.StarterServiceDeployer">
        <cfg:property name="config" value="service-starter.cfg"/>
    </cfg:component>
    
    <!-- Deployer for applications that are in the 'deploy' directory
    at startup. -->
    <cfg:component class="org.apache.river.container.deployer.FolderBasedAppRunner">
        <cfg:property name="deployDirectory" value="deploy"/>
        <cfg:property name="autoDeploy" value="true"/>
    </cfg:component>
    
    <!-- Deployer for 'system apps' like the remote deployment service 
    <cfg:component class="org.apache.river.container.deployer.StarterServiceDeployer">
        <cfg:property name="config" value="privileged-services.cfg"/>
        <cfg:property name="deployDirectory" value="deploy-privileged"/>
    </cfg:component>
    -->
    
    <cfg:component class="org.apache.river.container.ShowContextToConsole"/>
</cfg:container-config>
